[IDM-276] Support new introspect and consent policies in iam-operator
sugarcrm/hydra pull request #6
Opened 2018-01-22 13:49 UTC by ddolbik

2018-01-22 13:50 UTC, afedyk-sugarcrm approved these changes

2018-01-22 15:46 UTC, kolotaev requested changes

2018-01-22 15:46 UTC, kolotaev commented on Dockerfile
> -RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -X github.com/ory/hydra/cmd.Version=$git_tag -X github.com/ory/hydra/cmd.BuildTime=`TZ=UTC date -u '+%Y-%m-%dT%H:%M:%SZ'` -X github.com
Why the existing way of creating Hydra is not suitable for us?

2018-01-23 08:11 UTC, mgalagan-sugarcrm approved these changes

2018-01-23 10:41 UTC, kolotaev approved these changes

2018-02-09 15:18 UTC, alex-vlasov approved these changes

2018-02-12 08:22 UTC, merged